services:
   
      app:
         build: .
         ports:
           - "5001:5000"
         environment:
           DB_HOST: mysql
           DB_USER: root
           DB_PASSWORD: rootpassword
           DB_NAME: bookstore

         depends_on: 
                - mysql
                   
      mysql:
        image: mysql:8.0
        environment:
           MYSQL_ROOT_PASSWORD: rootpassword
           MYSQL_DATABASE: bookstore
        volumes:
          - sql_data:/var/lib/mysql

        
volumes:
        sql_data:                      