apiVersion: apps/v1

kind: Deployment

metadata:
     name: bookstore-deployment
     namespace: bookstore


spec:
    replicas: 2

    selector:
        matchLabels:
            app: bookstore

    template:
        metadata:
           labels:
             app: bookstore

        spec:
          containers:
             - name: bookstore
               image: nisha832/online-book-store:latest
               imagePullPolicy: IfNotPresent
               ports:
                 - containerPort: 5000
               resources:
                  requests:
                     cpu: "200m"
                     memory: "256Mi"
                  limits:
                     cpu: "500m"
                     memory: "512Mi"  

               livenessProbe:
                  httpGet:
                    path: /health 
                    port: 5000
                  initialDelaySeconds: 10
                  periodSeconds: 10

               readinessProbe:
                  httpGet: 
                    path: /health
                    port: 5000
                  initialDelaySeconds: 10
                  periodSeconds: 10              

               envFrom:
                - configMapRef:
                   name: bookstore-configmap   
               
                - secretRef: 
                   name: bookstore-secret   

